# Generated by Django 4.1.7 on 2023-04-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_category_image_item_image'),
        ('items', '0012_category_image_item_image_alter_order_total_price_and_more'),
    ]

    operations = [
    ]
